name: CSO_ML_Test
description: Demonstrates how to use the firebase_ml_vision plugin.
author: CSO

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^0.5.0
  cupertino_icons: ^0.1.2
  firebase_ml_vision: ^0.9.2
  firebase_core: ^0.4.0
  camera: ^0.5.2+1
  flutter_launcher_icons: ^0.7.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  path: ^1.6.2
  path_provider: ^0.5.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/Icon.png"